// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// C_sparcc
List C_sparcc(NumericMatrix x, int exiter, double thresh, int repEst);
RcppExport SEXP _NetCoMi_C_sparcc(SEXP xSEXP, SEXP exiterSEXP, SEXP threshSEXP, SEXP repEstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type exiter(exiterSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type repEst(repEstSEXP);
    rcpp_result_gen = Rcpp::wrap(C_sparcc(x, exiter, thresh, repEst));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NetCoMi_C_sparcc", (DL_FUNC) &_NetCoMi_C_sparcc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_NetCoMi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
