# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate correlations between taxa via SparCC algorithm
#'
#' @param x matrix with read counts
#' @param exiter maximum number of iterations, where in each step the
#'  strongest correlation is excluded and the basis variances and correlations
#'  are re-estimated based on the reduced data
#' @param thresh threshold for excluding component pairs in the
#'  iteration steps (pairs are excluded if the magnitude of their correlation
#'  value is upon the threshold)
#' @param repEst estimation process is repeated 'repEst' times to
#'  account for sampling noise; new fraction samples are drawn from Dirichlet
#'  distribution in each iteration step
#'
#'  @references{\insertRef{friedman2012inferring}{NetCoMi}}
C_sparcc <- function(x, exiter, thresh, repEst) {
    .Call(`_NetCoMi_C_sparcc`, x, exiter, thresh, repEst)
}

